config/routes.rb
Upcoming::Application.routes.draw do

  root :to => "pages#show", :page => "home"
  resources :events, :only => () do
    resources :registrations, :only => %w(new create)
  end
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_many :registrations
  has_many :events, :through => :registrations

  #validate :name, :email, :presence => true
  validates_presence_of :name, :email
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :registrations
  has_many :attendees, :through => :registrations
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :event
  belongs_to :attendee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    case params[:page]
    when "home"
      @events = Event.all
      render :action => "home"
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @registration = @event.registrations.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.erb
<li class="<%= dom_class(event) %>" id="<%= dom_id(event) %>">
  <%= link_to event.name, event.url %>
  <%= link_to "Register", new_event_registration_path(event) %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upcoming</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<% if @events.any? %>
<ol class="upcoming events">
  <%= render :partial => @events %>
</ol>
<% end %>